# Generated by Django 4.2.7 on 2023-11-21 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Employe',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='employe',
        ),
    ]
