# Generated by Django 4.2.7 on 2023-11-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_entreprise_administrateurplanning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employe',
            name='host',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='topic',
        ),
        migrations.AddField(
            model_name='employe',
            name='EntrepriseRattachée',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.entreprise'),
        ),
        migrations.AddField(
            model_name='employe',
            name='Poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.poste'),
        ),
    ]
