# Generated by Django 5.1.4 on 2025-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_week_first_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name='Shift en heures supplémentaires'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='couleur',
            field=models.CharField(choices=[('#FFFFFF', 'Blanc'), ('#ee96fa', 'Rose'), ('#96bcfa', 'Bleu'), ('#b7fa96', 'Vert'), ('#faf296', 'Jaune'), ('#FF0000', 'Rouge')], default='#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='teamplanning',
            name='TypeAbsence',
            field=models.CharField(choices=[('', "Sélectionnez un type d'absence"), ('Congé sans solde', 'Congé sans solde'), ('Congé payé', 'Congé payé'), ('Arrêt de travail', 'Arrêt de travail'), ('Autre..', 'Autre..')], default='Congé sans solde', max_length=25),
        ),
    ]
