# Generated by Django 4.2.7 on 2023-11-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_poste_remove_employe_host_remove_employe_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='description',
        ),
    ]
