# Generated by Django 4.2.7 on 2023-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_employe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='e_mail',
            field=models.CharField(default='default@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='employe',
            name='firstname',
            field=models.CharField(default='Default Firstname', max_length=200),
        ),
        migrations.AddField(
            model_name='employe',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=12),
        ),
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
    ]
