# Generated by Django 4.2.7 on 2023-12-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_teamplanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='Heurededébut',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.AddField(
            model_name='teamplanning',
            name='duréepause',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.AddField(
            model_name='teamplanning',
            name='heuredefin',
            field=models.CharField(default='Default Name', max_length=200),
        ),
    ]
