# Generated by Django 4.2.7 on 2024-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_teamplanning_heurededébut_teamplanning_duréepause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='firstname',
            field=models.CharField(default='Prénom', max_length=200),
        ),
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(default='Nom', max_length=200),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone_number',
            field=models.CharField(default='0634567890', max_length=12),
        ),
        migrations.AlterField(
            model_name='teamplanning',
            name='Heurededébut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='teamplanning',
            name='heuredefin',
            field=models.TimeField(),
        ),
    ]
