# Generated by Django 4.2.7 on 2024-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_employe_firstname_alter_employe_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
