# Generated by Django 4.2.7 on 2024-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_teamplanning_duréepause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.CharField(default='0000:', max_length=200),
        ),
    ]
