# Generated by Django 4.2.7 on 2024-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_teamplanning_duréepause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.CharField(default='prouty', max_length=200),
        ),
    ]
