# Generated by Django 4.2.7 on 2024-01-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_teamplanning_duréepause'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='note',
            field=models.CharField(default='prouty', max_length=200),
        ),
    ]
