# Generated by Django 4.2.7 on 2024-01-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_teamplanning_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='Poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.poste'),
        ),
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.CharField(default='00:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='teamplanning',
            name='note',
            field=models.CharField(max_length=200),
        ),
    ]
