# Generated by Django 4.2.7 on 2024-01-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_teamplanning_poste_alter_teamplanning_duréepause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.TimeField(default='00:00'),
        ),
    ]
