# Generated by Django 4.2.7 on 2024-01-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_teamplanning_duréepause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.TimeField(),
        ),
    ]
