# Generated by Django 4.2.7 on 2024-01-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_teamplanning_duréepause'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='Employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employe'),
        ),
    ]
