# Generated by Django 4.2.7 on 2024-01-11 13:26

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_teamplanning_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='Date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamplanning',
            name='duréepause',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
