# Generated by Django 4.2.7 on 2024-01-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_teamplanning_duréepause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplanning',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='teamplanning',
            name='Employe',
        ),
    ]
