# Generated by Django 4.2.7 on 2024-01-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_teamplanning_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplanning',
            name='Date',
        ),
    ]
