# Generated by Django 4.2.7 on 2024-01-11 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_teamplanning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
