# Generated by Django 4.2.7 on 2024-01-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_teamplanning_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamplanning',
            old_name='Date',
            new_name='date',
        ),
    ]
