# Generated by Django 4.2.7 on 2024-01-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_date_teamplanning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'White'), ('#808080', 'Gray'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FFFF00', 'Yellow')], default='#FF0000', max_length=7),
        ),
    ]
