# Generated by Django 4.2.7 on 2024-01-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_poste_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='color',
            field=models.CharField(choices=[('#FFFFFF', 'Blanc'), ('#808080', 'Gris'), ('#0000FF', 'Bleu'), ('#008000', 'Vert'), ('#FFFF00', 'Jaune')], default='#FF0000', max_length=7),
        ),
    ]
