# Generated by Django 4.2.7 on 2024-01-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_poste_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='color',
            new_name='couleur',
        ),
    ]
