# Generated by Django 4.2.7 on 2024-01-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_color_poste_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='couleur',
            field=models.CharField(choices=[('#FFFFFF', 'Blanc'), ('#808080', 'Gris'), ('#96bcfa', 'Bleu'), ('#008000', 'Vert'), ('#FFFF00', 'Jaune')], default='#FF0000', max_length=7),
        ),
    ]
