# Generated by Django 4.2.7 on 2024-01-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_poste_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='couleur',
            field=models.CharField(choices=[('#FFFFFF', 'Blanc'), ('#ee96fa', 'Rose'), ('#96bcfa', 'Bleu'), ('#b7fa96', 'Vert'), ('#faf296', 'Jaune')], default='#FF0000', max_length=7),
        ),
    ]
