# Generated by Django 4.2.7 on 2024-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_poste_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplanning',
            name='TypeAbsence',
            field=models.CharField(choices=[('Congé sans solde', 'Congé sans solde'), ('Congé payé', 'Congé payé')], default='Congé sans solde', max_length=25),
        ),
    ]
