# Generated by Django 4.2.7 on 2024-01-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_teamplanning_typeabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplanning',
            name='TypeAbsence',
            field=models.CharField(choices=[('', "Sélectionnez un type d'absence"), ('Congé sans solde', 'Congé sans solde'), ('Congé payé', 'Congé payé')], default='Congé sans solde', max_length=25),
        ),
    ]
