# Generated by Django 4.2.7 on 2024-02-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_teamplanning_typeabsence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
