# Generated by Django 4.2.7 on 2024-02-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypermissionsmodel',
            options={'permissions': (('Can manage a planning and its employes', 'Team Planning owner'),)},
        ),
    ]
