# Generated by Django 4.2.7 on 2024-02-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_mypermissionsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypermissionsmodel',
            options={'permissions': (('custom_permission', 'Team Planning owner'),)},
        ),
    ]
